blog/urls.py
from django.urls import path
from blog.views import SearchView, PostListView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('search/', SearchView.as_view(), name="blog-search"),
    path('blog/', PostListView.as_view(), name="blog"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="blog-details")
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required as __

from . import views
from .apis import SalesExpensesChart
from goals.views import Goals

"""
    In this urls.py file the login_required decorator will be used on all paths. 
    This insures that the user has to be authenticated to have access to this app's urls.
    
    !!!DO NOT REMOVE OR LEAVE PATHS WITHOUT USING THIS DECORATOR UNLESS THEY'RE FBV!!!
"""

app_name = 'dashboard'

urlpatterns = [
    path('', __(views.DashboardView.as_view()), name='dashboard'),
    path('new-client/', __(views.NewClientView.as_view()), name='new-client'),
    path('client/<int:pk>', __(views.ClientView.as_view()), name='client'),
    path('edit-client/<int:pk>', __(views.UpdateClientView.as_view()), name='edit-client'),
    path('delete-client/<int:pk>',  __(views.DeleteClient.as_view()), name='delete-client'),
    path('clients/', __(views.ClientsView.as_view()), name='clients'),
    path('new-invoice/', views.new_invoice, name='new-invoice'),
    path('invoices/', __(views.InvoiceList.as_view()), name='invoice-list'),
    path('pdf/<int:invoice_id>', views.generate_pdf, name='pdf'),
    path('zus/', __(views.ZusSettlementView.as_view()), name='zus'),
    path('profile/', __(views.Profile.as_view()), name='profile'),
    path('goals/', __(Goals.as_view()), name='goals'),

    # API's
    path('api/sales-expenses', __(SalesExpensesChart.as_view()), name="sales-expenses")
]

feedback/urls.py
from django.urls import path
from .views import JoinFormView

"""
    In this urls.py file the login_required decorator will be used on all paths. 
    This insures that the user has to be authenticated to have access to this app's urls.
    
    !!!DO NOT REMOVE OR LEAVE PATHS WITHOUT USING THIS DECORATOR UNLESS THEY'RE FBV!!!
"""

app_name = 'feedback'

urlpatterns = [
    path('feedback/', JoinFormView.as_view(), name="feedback"),
]

goals/urls.py
from django.urls import path

app_name = 'goals'

urlpatterns = [
    # Urls is set in the dashboard app for URL consistency
]

penge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += i18n_patterns(
    path('', include('accounts.urls')),
    path('', include('website.urls')),
    path('', include('blog.urls')),
    path('', include('feedback.urls')),
    path('dashboard/', include('dashboard.urls')),

    # 3th Party
    path('tinymce/', include('tinymce.urls')),
    path('inbox/notifications/', include('notifications.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms

from .models import Client, Invoice, InvoiceItem


class NewClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('co_nip_number',
                  'co_name',
                  'co_address',
                  'co_zip',
                  'co_city',
                  'co_country',
                  'co_telephone',
                  'co_email',
                  'co_logo')
        widgets = {'co_nip_number': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_address': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_zip': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_city': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_telephone': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'co_logo': forms.FileInput(attrs={'class': 'd-none cEvent'})}


class UpdateClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('co_nip_number',
                  'co_name',
                  'co_address',
                  'co_zip',
                  'co_city',
                  'co_country',
                  'co_telephone',
                  'co_email',
                  'co_website',
                  'co_att_person',
                  'co_payment_method',
                  'co_logo',
                  'in_currency',
                  'in_sendto_mail',
                  'in_sendto_subject',
                  'in_sendto_content',
                  'in_cc_mails',
                  'in_bcc_mails')
        widgets = {'co_nip_number': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_address': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_zip': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_city': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_telephone': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'co_website': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_att_person': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_logo': forms.FileInput(attrs={'class': 'd-none cEvent'}),
                   'in_currency': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_sendto_mail': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_sendto_subject': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_sendto_content': forms.Textarea(attrs={'class': 'form-control', "rows": 5, "cols": 20}),
                   'in_cc_mails': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_bcc_mails': forms.TextInput(attrs={'class': 'form-control'})}


class NewInvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ('client',
                  'place',
                  'date_deadline',
                  'custom_comment')
        widgets = {'date_deadline': forms.TimeInput(attrs={'class': 'form-control', 'type': 'date'}),
                   'place': forms.TextInput(attrs={'class': 'form-control'}),
                   'custom_comment': forms.TextInput(attrs={'class': 'form-control'})}


class InvoiceItemForm(forms.ModelForm):
    class Meta:
        model = InvoiceItem
        fields = ('service',
                  'unit_price',
                  'quantity',
                  'vat_rule',
                  'unit')
        widgets = {'service': forms.TextInput(attrs={'class': 'form-control'}),
                   'unit_price': forms.TextInput(attrs={'class': 'form-control'}),
                   'quantity': forms.TextInput(attrs={'class': 'form-control'})}

goals/forms.py
from django import forms


class FormStepOne(forms.Form):
    income = forms.DecimalField(decimal_places=2, max_digits=30)
    expenses = forms.DecimalField(decimal_places=2, max_digits=30)
    salary = forms. DecimalField(decimal_places=2, max_digits=30)
    email = forms.EmailField()


class FormStepTwo(forms.Form):
    job = forms.CharField(max_length=100)
    salary = forms.CharField(max_length=100)
    job_description = forms.CharField(widget=forms.Textarea)

dashboard/views.py
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, FormView, ListView, DeleteView, DetailView, UpdateView
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.shortcuts import redirect, render
from django.db.models import Max, Sum
from django.forms import inlineformset_factory
from django.template.loader import render_to_string
from django.db.models.functions import datetime
from django.utils import translation

from weasyprint import HTML
from datetime import date
from decimal import Decimal

import tempfile

from .forms import NewClientForm, NewInvoiceForm, UpdateClientForm
from .models import Client, InvoiceItem, Invoice, ExpensesToPay, ExpensesPaid
from accounts.models import Account

from accounts.forms import AccountEditForm


class DashboardView(DetailView):
    """
    The overview and the dashboard of a logged in user
    """
    template_name = 'dashboard/index.html'
    model = Account

    def get(self, request, *args, **kwargs):
        user = Account.objects.get(email=request.user)  # Set the user

        # Get the years of activity for the top chart
        # years = set()
        # for invoice in user.invoice.all():
        #     years.add(invoice.created_at.year)
        #     total = 0
        #     for item in invoice.items.all():
        #         result = Decimal(item.vat_rule)
        #         total += item.unit_price * item.quantity * (1 + result / 100)
        #     overall_item_total = round(total, 2)

        # Get the total income
        total_income = 0
        for i in user.invoice.all():
            for item in i.items.all():
                result = Decimal(item.vat_rule)
                total_income += item.unit_price * item.quantity * (1 + result / 100)
        sum_income = round(total_income, 2)
        # print(sum_income)

        # Get the total expenses
        total_paid = ExpensesPaid.objects.all().aggregate(Sum('price'))['price__sum'] or 0.00
        total_to_pay = ExpensesToPay.objects.all().aggregate(Sum('price'))['price__sum'] or 0.00
        sum_expenses = Decimal(total_paid) + Decimal(total_to_pay)
        # print(sum_expenses)

        # Expenses subtracted from Income
        total_earning = sum_income - sum_expenses

        # Check if the income is as expected in current year
        current_month = datetime.datetime.now().month
        current_year = datetime.datetime.now().year
        last_day_of_year = date(current_year, 12, 31)
        month_left = 12 - int(current_month)
        current_goal = 5000  # TODO: Make the client able to choose the goal
        goal_share = current_goal / 12

        if int(total_income) >= goal_share * int(current_month):
            business_status = 'Your business goes well'
        else:
            business_status = "Your business doesn't go well"
        print(month_left)
        print(current_year)

        # Clients count
        clients_amount = user.clients.count()

        context = {
            # 'years': years,
            'sum_income': sum_income,
            'sum_expenses': sum_expenses,
            'total_earning': total_earning,
            'business_status': business_status,
            'clients_amount': clients_amount
        }

        return render(request, template_name=self.template_name, context=context)


class Profile(UpdateView):
    """
    The users profile
    """
    template_name = 'dashboard/profile.html'
    form_class = AccountEditForm
    success_url = '/dashboard/profile'

    def get_object(self, *args, **kwargs):
        return self.request.user

    def post(self, request, **kwargs):
        if request.user.is_authenticated:
            translation.activate(request.user.language)
        return super(Profile, self).post(request, **kwargs)


class ClientView(ListView):
    """
    A Overview over a single clients details
    """
    model = Client
    ordering = ['-created_on']
    paginate_by = 10
    template_name = 'dashboard/client.html'

    def get_context_data(self, *args, **kwargs):
        client = Client.objects.get(pk=self.kwargs['pk'])
        context = {
            'client': client
        }

        return context


class UpdateClientView(UpdateView):
    """
    Update client details
    """
    form_class = UpdateClientForm
    model = Client
    template_name = 'dashboard/client-settings.html'
    success_url = 'dashboard/client-settings.html'


class ClientsView(ListView):
    """
    A list over clients
    """
    model = Client
    template_name = 'dashboard/clients.html'


class NewClientView(FormView):
    """
    A form to create new clients
    """
    form_class = NewClientForm
    template_name = 'dashboard/new-client.html'
    success_message = "Client was created successfully."

    def form_valid(self, form):
        # Getting the user who created the client
        contact = form.save(commit=False)
        contact.user = self.request.user
        contact.save()
        messages.success(self.request, self.success_message)

        return redirect('dashboard:clients')


class DeleteClient(DeleteView):
    """
    A view for deleting clients with AJAX at dashboard:clients
    """
    model = Client
    success_url = reverse_lazy('dashboard:clients')
    success_message = "Client was deleted successfully."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteClient, self).delete(request, *args, **kwargs)


def new_invoice(request):
    """
    A form to create and send an invoice to your clients
    """
    # Formset for items on the invoice (Services)
    invoice_formset = inlineformset_factory(
        Invoice,
        InvoiceItem,
        fields=('service',
                'unit_price',
                'quantity',
                'vat_rule',
                'unit'),
        can_delete=True
    )

    # Creating the invoice
    if request.method == 'POST':
        invoice_form = NewInvoiceForm(request.POST)
        if invoice_form.is_valid():
            invoice = invoice_form.save(commit=False)
            invoice.user = request.user  # Getting the user who created the invoice
            max_invoice_id = Invoice.objects.filter(user=request.user).aggregate(max_id=Max('invoice_id'))['max_id']
            if max_invoice_id:
                # check if it's not None (verify what returns aggregate() on empty queryset, adjust accordingly
                invoice.invoice_id = max_invoice_id + 1
            else:
                invoice.invoice_id = 1
            invoice.save()
            formset = invoice_formset(request.POST, instance=invoice)
            if formset.is_valid():
                formset.save(commit=False)
                total = 0
                for i in formset:
                    quantity = i.cleaned_data['quantity']
                    price = i.cleaned_data['unit_price']
                    vat = Decimal(i.cleaned_data['vat_rule'])
                    total += price * quantity * (1 + vat / 100)

                overall_invoice_total = round(total, 2)
                print(overall_invoice_total)
                invoice.total = overall_invoice_total
                invoice.save()
                formset.save()

                messages.success(request, "Invoice created.")

                return redirect('dashboard:dashboard')
        else:
            formset = invoice_formset()
            invoice_form = NewInvoiceForm()
    else:
        formset = invoice_formset()
        invoice_form = NewInvoiceForm()

    context = {
        'invoice_form': invoice_form,
        'formset': formset,
        'invoice': Invoice,
        'time': date,
        'city': Account.objects.only('co_city'),
        'pk': request.user.pk
    }
    return render(request, 'dashboard/new-invoice.html', context)


def generate_pdf(request, invoice_id):
    """
    Generate pdf using weasyprint
    """
    # Model data
    invoice = Invoice.objects.get(pk=invoice_id, user=request.user)
    client = Client.objects.all()
    invoice_items = invoice.items.all()

    # Gets the total price on the whole invoice and instance it to Invoice.total field
    total = 0
    for item in invoice_items:
        result = Decimal(item.vat_rule)
        total += item.unit_price * item.quantity * (1 + result / 100)

    overall_invoice_total = round(total, 2)
    Invoice.objects.create(total=overall_invoice_total)

    context = {
        'client': client,
        'invoice': invoice,
        'invoice_items': invoice_items,
        'total': overall_invoice_total
    }

    # Rendered
    html_string = render_to_string('emails/invoice.html', context)
    html = HTML(string=html_string)
    result = html.write_pdf()

    # Creating http response
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=list_people.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')  # rb for 'Read Binary'
        response.write(output.read())

    return response


class ZusSettlementView(TemplateView):
    """
        A guide to fill out ZUS applications
    """
    template_name = 'dashboard/zus-settlement.html'

    def get_context_data(self, *args, **kwargs):
        context = {
            'page_title': 'ZUS'
        }

        return context


class InvoiceList(ListView):
    """
        A list over Invoices sent
    """
    template_name = 'dashboard/invoice-list.html'
    model = Invoice

goals/views.py
from django.shortcuts import render
from django.views.generic import FormView
from formtools.wizard.views import SessionWizardView

from .forms import FormStepOne, FormStepTwo


class Goals(SessionWizardView):
    template_name = 'dashboard/goals.html'
    form_list = [FormStepOne, FormStepTwo]

    def done(self, form_list, **kwargs):
        return render(self.request, 'dashboard/done-goal.html', {
            'form_data': [form.cleaned_data for form in form_list],
        })

content/templates/dashboard/clients.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Client Overview' %}{% endblock %}
{% block customcss %}
    <style>
        #clientBtnDrop {
            display: block;
            position: absolute;
            right: 0;
            z-index: 999;
            border: none;
            background: #353c48;
        }

        #clientBtnDrop:focus,
        .delete-client:focus {
            border: none;
            outline: none;
            box-shadow: none;
        }

        .delete-client:hover {
            color: red;
        }

        .delete-client {
            color: red;
            border: none;
        }
        .nothingHere i:before {
            font-size: 20vw;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for client in object_list %}
                <div id="client-{{ client.pk }}" class="col-md-6 col-lg-6 col-xlg-4">
                    <div class="card card-body">
                        <div class="btn-group clientSettings" role="group">
                            <button id="clientBtnDrop" type="button" class="btn btn-secondary"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="ti-more-alt"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="clientBtnDrop">
                                <a class="dropdown-item" href="{% url 'dashboard:edit-client' client.pk %}">
                                    <i class="ti-pencil"></i> {% trans 'Edit' %}
                                </a>
                                <form method="POST" action="{% url 'dashboard:delete-client' client.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item delete-client">
                                        <i class="ti-minus"></i> {% trans 'Delete' %}
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="row align-items-center">
                            <div class="col-md-4 col-lg-3 text-center">
                                <a href="#">
                                    <img src="{{ client.co_logo.url }}" alt="user"
                                         class="clientProfileImage img-circle img-fluid">
                                </a>
                            </div>
                            <div class="col-md-8 col-lg-9">
                                <h3 class="box-title m-b-0">
                                    <a href="{% url 'dashboard:client' client.pk %}">{{ client.co_name }}</a>
                                </h3>
                                <small>{% trans 'NIP:' %} {{ client.co_nip_number }}</small>
                                <address>
                                    {{ client.co_address }}, {{ client.co_zip }}, {{ client.co_city }}
                                    <br/>
                                    <br/>
                                    <p title="Phone">
                                        <i class="ti-mobile"></i> {{ client.co_telephone }}
                                    </p>
                                    <p title="Email">
                                        <i class="ti-email"></i> {{ client.co_email }}
                                    </p>
                                </address>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="col-md-12 text-center nothingHere">
                    <h2 class="">{% trans 'Snap, no clients was found' %}</h2>
                    <h5 class="">{% trans 'Clients make it easy to put invoicing on auto pilot, and send a invoice in less than a minute!' %}</h5>
                    <i class="ti-face-sad mt-5 mb-5 d-block"></i>
                    <a href="{% url 'dashboard:new-client' %}" class="btn btn-primary">{% trans 'Make your first client now' %}</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block customjs %}
    <script>
        $(document).ready(function () {
            // Add max-height or max-width depending on image being vertical or horizontal
            $('img.clientProfileImage').each(function () {
                if ($(this).width() > $(this).height()) {
                    $("img.clientProfileImage").css("max-width", "130px");
                } else {
                    $("img.clientProfileImage").css("max-height", "130px");
                }
            });
        });
    </script>
{% endblock %}

content/templates/dashboard/done-goal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

content/templates/dashboard/goals.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block customcss %}

{% endblock %}
{% block title %}Company Goals{% endblock %}
{% block content %}
    <div class="row">
        <!-- Column -->
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
                        <form action="" method="post">
                            {% csrf_token %}
                            <table>
                                {{ wizard.management_form }}
                                {% if wizard.form.forms %}
                                    {{ wizard.form.management_form }}
                                    {% for form in wizard.form.forms %}
                                        {{ form }}
                                    {% endfor %}
                                {% else %}
                                    {{ wizard.form }}
                                {% endif %}
                            </table>
                            {% if wizard.steps.prev %}
                                <button name="wizard_goto_step" type="submit"
                                        value="{{ wizard.steps.first }}">First step
                                </button>
                                <button name="wizard_goto_step" type="submit"
                                        value="{{ wizard.steps.prev }}">Previous step
                                </button>
                            {% endif %}
                            <input type="submit" value="submit"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block customjs %}
    <script>
        $('form').on('submit', '#creation-form', function (e) {
            e.preventDefault();

            let post_data = $(this).serialize();
            console.log('POST data:' + post_data);

            $.ajax({
                url: '/create/',
                data: post_data,
                type: "POST",
                success: function (resp) {
                    console.log(resp);
                    $('#creation').html(resp);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(jqXHR);
                    console.log(textStatus);
                    console.log(errorThrown);
                },
                processData: false,
                contentType: false
            });
        });
    </script>
{% endblock %}

content/templates/dashboard/invoice-list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load i18n %}
{% block customcss %}{% endblock %}
{% block title %}{% trans 'Sent Invoices' %}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <!-- Column -->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>{% trans 'Date' %}</th>
                                    <th>{% trans 'Deadline' %}</th>
                                    <th>{% trans 'Client' %}</th>
                                    <th>{% trans 'Total' %}</th>
                                    <th>{% trans 'Status' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for invoice in object_list %}
                                <tr>
                                    <td><a href="javascript:void(0)">#{{ invoice.invoice_id }}</a></td>
                                    <td>{{ invoice.created_at|date:"d M. Y" }}</td>
                                    <td><span class="text-muted"><i class="fa fa-clock-o"></i> {{ invoice.date_deadline|date:"d M. Y" }}</span></td>
                                    <td>{{ invoice.client.co_name }}</td>
                                    <td>{{ invoice.created_at|date:"D d M Y" }}</td>
                                    <td>
                                        <div class="label label-table label-success">Paid</div>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block customjs %}
{% endblock %}