accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

blog/urls.py
from django.urls import path
from blog.views import SearchView, PostListView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('search/', SearchView.as_view(), name="blog-search"),
    path('blog/', PostListView.as_view(), name="blog"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="blog-details")
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required as __

from . import views
from .apis import SalesExpensesChart
from goals.views import Goals

"""
    In this urls.py file the login_required decorator will be used on all paths. 
    This insures that the user has to be authenticated to have access to this app's urls.
    
    !!!DO NOT REMOVE OR LEAVE PATHS WITHOUT USING THIS DECORATOR UNLESS THEY'RE FBV!!!
"""

app_name = 'dashboard'

urlpatterns = [
    path('', __(views.DashboardView.as_view()), name='dashboard'),
    path('new-client/', __(views.NewClientView.as_view()), name='new-client'),
    path('client/<int:pk>', __(views.ClientView.as_view()), name='client'),
    path('edit-client/<int:pk>', __(views.UpdateClientView.as_view()), name='edit-client'),
    path('delete-client/<int:pk>',  __(views.DeleteClient.as_view()), name='delete-client'),
    path('clients/', __(views.ClientsView.as_view()), name='clients'),
    path('new-invoice/', views.new_invoice, name='new-invoice'),
    path('invoices/', __(views.InvoiceList.as_view()), name='invoice-list'),
    path('pdf/<int:invoice_id>', views.generate_pdf, name='pdf'),
    path('zus/', __(views.ZusSettlementView.as_view()), name='zus'),
    path('profile/', __(views.Profile.as_view()), name='profile'),
    path('goals/', __(Goals.as_view()), name='goals'),

    # API's
    path('api/sales-expenses', __(SalesExpensesChart.as_view()), name="sales-expenses")
]

penge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += i18n_patterns(
    path('', include('accounts.urls')),
    path('', include('website.urls')),
    path('', include('blog.urls')),
    path('', include('feedback.urls')),
    path('dashboard/', include('dashboard.urls')),

    # 3th Party
    path('tinymce/', include('tinymce.urls')),
    path('inbox/notifications/', include('notifications.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms

from .models import Client, Invoice, InvoiceItem


class NewClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('co_nip_number',
                  'co_name',
                  'co_address',
                  'co_zip',
                  'co_city',
                  'co_country',
                  'co_telephone',
                  'co_email',
                  'co_logo')
        widgets = {'co_nip_number': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_address': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_zip': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_city': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_telephone': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'co_logo': forms.FileInput(attrs={'class': 'd-none cEvent'})}


class UpdateClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('co_nip_number',
                  'co_name',
                  'co_address',
                  'co_zip',
                  'co_city',
                  'co_country',
                  'co_telephone',
                  'co_email',
                  'co_website',
                  'co_att_person',
                  'co_payment_method',
                  'co_logo',
                  'in_currency',
                  'in_sendto_mail',
                  'in_sendto_subject',
                  'in_sendto_content',
                  'in_cc_mails',
                  'in_bcc_mails')
        widgets = {'co_nip_number': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_address': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_zip': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_city': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_telephone': forms.NumberInput(attrs={'class': 'form-control'}),
                   'co_email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'co_website': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_att_person': forms.TextInput(attrs={'class': 'form-control'}),
                   'co_logo': forms.FileInput(attrs={'class': 'd-none cEvent'}),
                   'in_currency': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_sendto_mail': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_sendto_subject': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_sendto_content': forms.Textarea(attrs={'class': 'form-control', "rows": 5, "cols": 20}),
                   'in_cc_mails': forms.TextInput(attrs={'class': 'form-control'}),
                   'in_bcc_mails': forms.TextInput(attrs={'class': 'form-control'})}


class NewInvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ('client',
                  'place',
                  'date_deadline',
                  'custom_comment')
        widgets = {'date_deadline': forms.TimeInput(attrs={'class': 'form-control', 'type': 'date'}),
                   'place': forms.TextInput(attrs={'class': 'form-control'}),
                   'custom_comment': forms.TextInput(attrs={'class': 'form-control'})}


class InvoiceItemForm(forms.ModelForm):
    class Meta:
        model = InvoiceItem
        fields = ('service',
                  'unit_price',
                  'quantity',
                  'vat_rule',
                  'unit')
        widgets = {'service': forms.TextInput(attrs={'class': 'form-control'}),
                   'unit_price': forms.TextInput(attrs={'class': 'form-control'}),
                   'quantity': forms.TextInput(attrs={'class': 'form-control'})}

dashboard/views.py
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, FormView, ListView, DeleteView, DetailView, UpdateView
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.shortcuts import redirect, render
from django.db.models import Max, Sum
from django.forms import inlineformset_factory
from django.template.loader import render_to_string
from django.db.models.functions import datetime
from django.utils import translation

from weasyprint import HTML
from datetime import date
from decimal import Decimal

import tempfile

from .forms import NewClientForm, NewInvoiceForm, UpdateClientForm
from .models import Client, InvoiceItem, Invoice, ExpensesToPay, ExpensesPaid
from accounts.models import Account

from accounts.forms import AccountEditForm


class DashboardView(DetailView):
    """
    The overview and the dashboard of a logged in user
    """
    template_name = 'dashboard/index.html'
    model = Account

    def get(self, request, *args, **kwargs):
        user = Account.objects.get(email=request.user)  # Set the user

        # Get the years of activity for the top chart
        # years = set()
        # for invoice in user.invoice.all():
        #     years.add(invoice.created_at.year)
        #     total = 0
        #     for item in invoice.items.all():
        #         result = Decimal(item.vat_rule)
        #         total += item.unit_price * item.quantity * (1 + result / 100)
        #     overall_item_total = round(total, 2)

        # Get the total income
        total_income = 0
        for i in user.invoice.all():
            for item in i.items.all():
                result = Decimal(item.vat_rule)
                total_income += item.unit_price * item.quantity * (1 + result / 100)
        sum_income = round(total_income, 2)
        # print(sum_income)

        # Get the total expenses
        total_paid = ExpensesPaid.objects.all().aggregate(Sum('price'))['price__sum'] or 0.00
        total_to_pay = ExpensesToPay.objects.all().aggregate(Sum('price'))['price__sum'] or 0.00
        sum_expenses = Decimal(total_paid) + Decimal(total_to_pay)
        # print(sum_expenses)

        # Expenses subtracted from Income
        total_earning = sum_income - sum_expenses

        # Check if the income is as expected in current year
        current_month = datetime.datetime.now().month
        current_year = datetime.datetime.now().year
        last_day_of_year = date(current_year, 12, 31)
        month_left = 12 - int(current_month)
        current_goal = 5000  # TODO: Make the client able to choose the goal
        goal_share = current_goal / 12

        if int(total_income) >= goal_share * int(current_month):
            business_status = 'Your business goes well'
        else:
            business_status = "Your business doesn't go well"
        print(month_left)
        print(current_year)

        # Clients count
        clients_amount = user.clients.count()

        context = {
            # 'years': years,
            'sum_income': sum_income,
            'sum_expenses': sum_expenses,
            'total_earning': total_earning,
            'business_status': business_status,
            'clients_amount': clients_amount
        }

        return render(request, template_name=self.template_name, context=context)


class Profile(UpdateView):
    """
    The users profile
    """
    template_name = 'dashboard/profile.html'
    form_class = AccountEditForm
    success_url = '/dashboard/profile'

    def get_object(self, *args, **kwargs):
        return self.request.user

    def post(self, request, **kwargs):
        if request.user.is_authenticated:
            translation.activate(request.user.language)
        return super(Profile, self).post(request, **kwargs)


class ClientView(ListView):
    """
    A Overview over a single clients details
    """
    model = Client
    ordering = ['-created_on']
    paginate_by = 10
    template_name = 'dashboard/client.html'

    def get_context_data(self, *args, **kwargs):
        client = Client.objects.get(pk=self.kwargs['pk'])
        context = {
            'client': client
        }

        return context


class UpdateClientView(UpdateView):
    """
    Update client details
    """
    form_class = UpdateClientForm
    model = Client
    template_name = 'dashboard/client-settings.html'
    success_url = 'dashboard/client-settings.html'


class ClientsView(ListView):
    """
    A list over clients
    """
    model = Client
    template_name = 'dashboard/clients.html'


class NewClientView(FormView):
    """
    A form to create new clients
    """
    form_class = NewClientForm
    template_name = 'dashboard/new-client.html'
    success_message = "Client was created successfully."

    def form_valid(self, form):
        # Getting the user who created the client
        contact = form.save(commit=False)
        contact.user = self.request.user
        contact.save()
        messages.success(self.request, self.success_message)

        return redirect('dashboard:clients')


class DeleteClient(DeleteView):
    """
    A view for deleting clients with AJAX at dashboard:clients
    """
    model = Client
    success_url = reverse_lazy('dashboard:clients')
    success_message = "Client was deleted successfully."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteClient, self).delete(request, *args, **kwargs)


def new_invoice(request):
    """
    A form to create and send an invoice to your clients
    """
    # Formset for items on the invoice (Services)
    invoice_formset = inlineformset_factory(
        Invoice,
        InvoiceItem,
        fields=('service',
                'unit_price',
                'quantity',
                'vat_rule',
                'unit'),
        can_delete=True
    )

    # Creating the invoice
    if request.method == 'POST':
        invoice_form = NewInvoiceForm(request.POST)
        if invoice_form.is_valid():
            invoice = invoice_form.save(commit=False)
            invoice.user = request.user  # Getting the user who created the invoice
            max_invoice_id = Invoice.objects.filter(user=request.user).aggregate(max_id=Max('invoice_id'))['max_id']
            if max_invoice_id:
                # check if it's not None (verify what returns aggregate() on empty queryset, adjust accordingly
                invoice.invoice_id = max_invoice_id + 1
            else:
                invoice.invoice_id = 1
            invoice.save()
            formset = invoice_formset(request.POST, instance=invoice)
            if formset.is_valid():
                formset.save(commit=False)
                total = 0
                for i in formset:
                    quantity = i.cleaned_data['quantity']
                    price = i.cleaned_data['unit_price']
                    vat = Decimal(i.cleaned_data['vat_rule'])
                    total += price * quantity * (1 + vat / 100)

                overall_invoice_total = round(total, 2)
                print(overall_invoice_total)
                invoice.total = overall_invoice_total
                invoice.save()
                formset.save()

                messages.success(request, "Invoice created.")

                return redirect('dashboard:dashboard')
        else:
            formset = invoice_formset()
            invoice_form = NewInvoiceForm()
    else:
        formset = invoice_formset()
        invoice_form = NewInvoiceForm()

    context = {
        'invoice_form': invoice_form,
        'formset': formset,
        'invoice': Invoice,
        'time': date,
        'city': Account.objects.only('co_city'),
        'pk': request.user.pk
    }
    return render(request, 'dashboard/new-invoice.html', context)


def generate_pdf(request, invoice_id):
    """
    Generate pdf using weasyprint
    """
    # Model data
    invoice = Invoice.objects.get(pk=invoice_id, user=request.user)
    client = Client.objects.all()
    invoice_items = invoice.items.all()

    # Gets the total price on the whole invoice and instance it to Invoice.total field
    total = 0
    for item in invoice_items:
        result = Decimal(item.vat_rule)
        total += item.unit_price * item.quantity * (1 + result / 100)

    overall_invoice_total = round(total, 2)
    Invoice.objects.create(total=overall_invoice_total)

    context = {
        'client': client,
        'invoice': invoice,
        'invoice_items': invoice_items,
        'total': overall_invoice_total
    }

    # Rendered
    html_string = render_to_string('emails/invoice.html', context)
    html = HTML(string=html_string)
    result = html.write_pdf()

    # Creating http response
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=list_people.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')  # rb for 'Read Binary'
        response.write(output.read())

    return response


class ZusSettlementView(TemplateView):
    """
        A guide to fill out ZUS applications
    """
    template_name = 'dashboard/zus-settlement.html'

    def get_context_data(self, *args, **kwargs):
        context = {
            'page_title': 'ZUS'
        }

        return context


class InvoiceList(ListView):
    """
        A list over Invoices sent
    """
    template_name = 'dashboard/invoice-list.html'
    model = Invoice

content/templates/dashboard/inc/header.html
{% load static %}
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">
                <b>
                    <img src="{% static "general/logo-icon-50.png" %}" alt="homepage" class="light-logo" />
                </b>
                <span>
                    <img src="{% static "general/logo-text-100.png" %}" class="light-logo" alt="homepage" />
                </span>
            </a>
        </div>
        <div class="navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"> <a class="nav-link nav-toggler d-block d-md-none waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                <li class="nav-item"> <a class="nav-link sidebartoggler d-none d-lg-block d-md-block waves-effect waves-dark" href="javascript:void(0)"><i class="icon-menu"></i></a> </li>
                <li class="nav-item">
                    <form class="app-search d-none d-md-block d-lg-block">
                        <input type="text" class="form-control" placeholder="Search for clients">
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav my-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="ti-bell"></i>
                        <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown">
                        <ul>
                            <li>
                                <div class="drop-title">Notifications</div>
                            </li>
                            <li>
                                <div class="message-center">
                                    <a href="javascript:void(0)">
                                        <div class="btn btn-danger btn-circle"><i class="fa fa-link"></i></div>
                                        <div class="mail-contnet">
                                            <h5>Luanch Admin</h5> <span class="mail-desc">Just see the my new admin!</span> <span class="time">9:30 AM</span> </div>
                                    </a>
                                    <a href="javascript:void(0)">
                                        <div class="btn btn-success btn-circle"><i class="ti-calendar"></i></div>
                                        <div class="mail-contnet">
                                            <h5>Event today</h5> <span class="mail-desc">Just a reminder that you have event</span> <span class="time">9:10 AM</span> </div>
                                    </a>
                                    <a href="javascript:void(0)">
                                        <div class="btn btn-info btn-circle"><i class="ti-settings"></i></div>
                                        <div class="mail-contnet">
                                            <h5>Settings</h5> <span class="mail-desc">You can customize this template as you want</span> <span class="time">9:08 AM</span> </div>
                                    </a>
                                    <a href="javascript:void(0)">
                                        <div class="btn btn-primary btn-circle"><i class="ti-user"></i></div>
                                        <div class="mail-contnet">
                                            <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </div>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <a class="nav-link text-center link" href="javascript:void(0);"> <strong>Check all notifications</strong> <i class="fa fa-angle-right"></i> </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="icon-question"></i>
                    </a>
                    <div class="dropdown-menu mailbox dropdown-menu-right animated bounceInDown" aria-labelledby="2">
                        <ul>
                            <li>
                                <div class="drop-title">Find answers on basic accounting questions</div>
                            </li>
                            <li>
                                <div class="message-center">
                                    <a href="javascript:void(0)">
                                        <div class="user-img"> <img src="../assets/images/users/1.jpg" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>
                                        <div class="mail-contnet">
                                            <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </div>
                                    </a>
                                    <a href="javascript:void(0)">
                                        <div class="user-img"> <img src="../assets/images/users/2.jpg" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
                                        <div class="mail-contnet">
                                            <h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </div>
                                    </a>
                                    <a href="javascript:void(0)">
                                        <div class="user-img"> <img src="../assets/images/users/3.jpg" alt="user" class="img-circle"> <span class="profile-status away pull-right"></span> </div>
                                        <div class="mail-contnet">
                                            <h5>Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span> </div>
                                    </a>
                                    <a href="javascript:void(0)">
                                        <div class="user-img"> <img src="../assets/images/users/4.jpg" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span> </div>
                                        <div class="mail-contnet">
                                            <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </div>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <a class="nav-link text-center link" href="javascript:void(0);"> <strong>See all e-Mails</strong> <i class="fa fa-angle-right"></i> </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>

content/templates/dashboard/inc/left-sidebar.html
{% load static %}
<aside class="left-sidebar">
    <div class="scroll-sidebar">
        <div class="user-profile">
            <div class="user-pro-body">
                <div><img src="{% static "dashboard/images/users/2.jpg" %}" alt="user-img" class="img-circle"></div>
                <div class="dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle u-dropdown link hide-menu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Woprun ApS <span class="caret"></span></a>
                    <div class="dropdown-menu animated flipInY">
                        <a href="javascript:void(0)" class="dropdown-item">
                            <i class="ti-user"></i> My Profile
                        </a>
                        <a href="javascript:void(0)" class="dropdown-item">
                            <i class="ti-wallet"></i> My Balance
                        </a>
                        <a href="javascript:void(0)" class="dropdown-item">
                            <i class="ti-email"></i> Inbox
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="javascript:void(0)" class="dropdown-item">
                            <i class="ti-settings"></i> Account Setting
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'accounts:logout' %}" class="dropdown-item">
                            <i class="fas fa-power-off"></i> Logout
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-small-cap">--- MENU</li>
                <li>
                    <a href="{% url 'dashboard:dashboard' %}" aria-expanded="false">
                        <i class="icon-speedometer"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a class="has-arrow" href="javascript:void(0)" aria-expanded="false">
                        <i class="ti-user"></i>
                        <span class="hide-menu">Clients</span>
                    </a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{% url 'dashboard:clients' %}">Clients</a></li>
                        <li><a href="{% url 'dashboard:new-client' %}">New Client</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'dashboard:zus' %}" aria-expanded="false">
                        <i class="ti-menu-alt"></i>
                        <span class="hide-menu">Settle ZUS</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

content/templates/dashboard/inc/right-sidebar.html
<div class="right-sidebar">
    <div class="slimscrollright">
        <div class="rpanel-title"> Service Panel <span><i class="ti-close right-side-toggle"></i></span> </div>
        <div class="r-panel-body">
            <ul id="themecolors" class="m-t-20">
                <li><b>With Light sidebar</b></li>
                <li><a href="javascript:void(0)" data-skin="skin-default" class="default-theme">1</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-green" class="green-theme">2</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-red" class="red-theme">3</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-blue" class="blue-theme">4</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-purple" class="purple-theme">5</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-megna" class="megna-theme">6</a></li>
                <li class="d-block m-t-30"><b>With Dark sidebar</b></li>
                <li><a href="javascript:void(0)" data-skin="skin-default-dark" class="default-dark-theme working">7</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-green-dark" class="green-dark-theme">8</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-red-dark" class="red-dark-theme">9</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-blue-dark" class="blue-dark-theme">10</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-purple-dark" class="purple-dark-theme">11</a></li>
                <li><a href="javascript:void(0)" data-skin="skin-megna-dark" class="megna-dark-theme ">12</a></li>
            </ul>
            <ul class="m-t-20 chatonline">
                <li><b>Chat option</b></li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/1.jpg" alt="user-img" class="img-circle"> <span>Varun Dhavan <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/2.jpg" alt="user-img" class="img-circle"> <span>Genelia Deshmukh <small class="text-warning">Away</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/3.jpg" alt="user-img" class="img-circle"> <span>Ritesh Deshmukh <small class="text-danger">Busy</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/4.jpg" alt="user-img" class="img-circle"> <span>Arijit Sinh <small class="text-muted">Offline</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/5.jpg" alt="user-img" class="img-circle"> <span>Govinda Star <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/6.jpg" alt="user-img" class="img-circle"> <span>John Abraham<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/7.jpg" alt="user-img" class="img-circle"> <span>Hritik Roshan<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="../assets/images/users/8.jpg" alt="user-img" class="img-circle"> <span>Pwandeep rajan <small class="text-success">online</small></span></a>
                </li>
            </ul>
        </div>
    </div>
</div>