blog/urls.py
from django.urls import path
from blog.views import SearchView, PostListView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('search/', SearchView.as_view(), name="blog-search"),
    path('blog/', PostListView.as_view(), name="blog"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="blog-details")
]

penge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += i18n_patterns(
    path('', include('accounts.urls')),
    path('', include('website.urls')),
    path('', include('blog.urls')),
    path('', include('feedback.urls')),
    path('dashboard/', include('dashboard.urls')),

    # 3th Party
    path('tinymce/', include('tinymce.urls')),
    path('inbox/notifications/', include('notifications.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.HomeView.as_view(), name="w-home-view"),
    path('contact/', views.ContactView.as_view(), name="w-contact-view"),
    path('blog/', views.BlogView.as_view(), name="w-blog-view"),
    path('blog/results/', views.search, name="w-blog-results-view"),
    path('post/<id>/', views.BlogDetailView.as_view(), name="w-blog-details-view"),
    path('features/', views.FeaturesView.as_view(), name="w-features-view"),
    path('pricing', views.PricingView.as_view(), name="w-pricing-view")
]

blog/models.py
from tinymce import HTMLField
from django.db import models
from django.urls import reverse

from accounts.models import Account


class PostView(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Author(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    content = HTMLField()
    comment_count = models.IntegerField(default=0)
    view_count = models.IntegerField(default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-details', kwargs={
            'pk': self.pk
        })

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

website/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content', 'thumbnail',
                  'categories', 'featured', 'previous_post', 'next_post')


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4'
    }))

    class Meta:
        model = Comment
        fields = ('content',)

website/forms.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    name = forms.CharField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.db.models import Count, Q
from django.shortcuts import render, redirect, reverse
from django.views.generic import View, ListView, DetailView

from .forms import CommentForm
from .models import Post, Author, PostView
from marketing.forms import EmailSignupForm

form = EmailSignupForm()


class SearchView(View):
    def get(self, request, *args, **kwargs):
        queryset = Post.objects.all()
        query = request.GET.get('q')

        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(overview__icontains=query)
            ).distinct()

        context = {
            'queryset': queryset
        }

        return render(request, 'website/results.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'website/blog.html'
    context_object_name = 'queryset'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count

        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'website/blog-details.html'
    context_object_name = 'post'
    form = CommentForm()

    def get_object(self):
        obj = super().get_object()

        if self.request.user.is_authenticated:
            PostView.objects.get_or_create(
                user=self.request.user,
                post=obj
            )

        return obj

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['form'] = self.form

        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)

        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()

            return redirect(reverse("blog:blog-details", kwargs={
                'pk': post.pk
            }))


def get_author(user):
    qs = Author.objects.filter(user=user)

    if qs.exists():
        return qs[0]

    return None


def get_category_count():
    queryset = Post \
        .objects \
        .values('categories__title') \
        .annotate(Count('categories__title'))

    return queryset

website/views.py
from django.views import View
from django.views.generic import TemplateView, ListView, FormView, DetailView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db.models import Q
from djstripe.models import Product

from blog.models import Post
from .forms import ContactForm


class HomeView(TemplateView):
    template_name = 'website/index.html'


class BlogView(ListView):
    template_name = 'website/blog.html'
    model = Post
    paginate_by = 4


class ContactView(FormView):
    template_name = 'website/contact.html'
    form = ContactForm
    success_url = ''

    def form_valid(self, *args, form):
        subject = form.cleaned_data['subject']
        from_email = form.cleaned_data['from_email']
        message = form.cleaned_data['message']
        try:
            send_mail(subject, message, from_email, ['admin@example.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return redirect('success')

    def get(self, request, *args):
        return render(request, self.template_name, {'form': self.form})


class BlogDetailView(DetailView):
    template_name = 'website/blog-details.html'
    model = Post
    pk_url_kwarg = 'id'


class PricingView(View):
    template_name = 'website/pricing.html'

    def get(self, request, *args, **kwargs):
        # Get all Pricing models in our DB
        products = Product.objects.all()
        return render(request, self.template_name, {'products': products})


class FeaturesView(TemplateView):
    template_name = 'website/features.html'


def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)
        ).distinct()

    context = {
        'queryset': queryset
    }

    return render(request, 'website/results.html', context)

content/templates/website/base.html
{% load static %}
{% load svg %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create a FREE account at Penge - Poland's easiest online accounting</title>
    <link rel="icon" href="img/Fevicon.png" type="image/png">
    <link rel="stylesheet" href="{% static 'website/vendors/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendors/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendors/themify-icons/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendors/linericon/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendors/owl-carousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendors/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
<header class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container box_1620">
                <a class="navbar-brand logo_h" href="index.html">
                    <img src="img/logo.png" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav justify-content-end">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'website:w-home-view' %}">Home</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'website:w-features-view' %}">Features</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'website:w-blog-view' %}">Blog</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'website:w-pricing-view' %}">Price</a>
                        <li class="nav-item"><a class="nav-link" href="{% url 'website:w-contact-view' %}">Contact</a>
                        </li>
                    </ul>
                    <ul class="navbar-right">
                        <li class="nav-item">
                            <button class="button button-header bg">Sign up</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>
{% block content %}{% endblock %}
<footer class="footer-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-xl-2 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                <h4>{% trans 'Penge' %}</h4>
                <ul>
                    <li><a href="#">{% trans 'Features' %}</a></li>
                    <li><a href="#">{% trans 'Contact' %}</a></li>
                    <li><a href="#">{% trans 'About Us' %}</a></li>
                    <li><a href="#">{% trans 'Why Penge?' %}</a></li>
                </ul>
            </div>
            <div class="col-xl-2 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                <h4>{% trans 'Information' %}</h4>
                <ul>
                    <li><a href="#">{% trans 'Jobs' %}</a></li>
                    <li><a href="#">{% trans 'Investor Relations' %}</a></li>
                    <li><a href="#">{% trans 'Terms of Conditions' %}</a></li>
                    <li><a href="#">{% trans 'Terms of Service' %}</a></li>
                </ul>
            </div>
            <div class="col-xl-2 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                <h4>{% trans 'Help' %}</h4>
                <ul>
                    <li><a href="#">{% trans 'Who is Penge for?' %}</a></li>
                    <li><a href="#">{% trans 'Start a company in Poland' %}</a></li>
                    <li><a href="#">{% trans 'Currency Calculator' %}</a></li>
                    <li><a href="#">{% trans 'Accounting Courses' %}</a></li>
                </ul>
            </div>
            <div class="col-xl-2 col-sm-6 mb-4 mb-xl-0 single-footer-widget">

            </div>
            <div class="col-xl-4 col-md-8 mb-4 mb-xl-0 single-footer-widget">
                <h4>{% trans 'Newsletter' %}</h4>
                <p>{% trans 'Recieve company related value directly on your e-mail' %}</p>
                <div class="form-wrap" id="mc_embed_signup">
                    <form target="_blank" action="" method="get" class="form-inline">
                        {% csrf_token %}
                        {{ email_subscription_form.email }}
                        <button class="click-btn btn btn-default">{% trans 'Subscribe' %}</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-bottom row align-items-center text-center text-lg-left">
            <p class="footer-text m-0 col-lg-8 col-md-12">
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | Penge
            </p>
            <div class="col-lg-4 col-md-12 text-center text-lg-right footer-social">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-dribbble"></i></a>
                <a href="#"><i class="fab fa-behance"></i></a>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'website/vendors/jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'website/vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'website/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'website/js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'website/js/mail-script.js' %}"></script>
<script src="{% static 'website/js/main.js' %}"></script>
</body>
</html>

content/templates/website/contact.html
{% extends 'website/base.html' %}
{% block content %}
<!--================ Hero sm Banner start =================-->
<section class="hero-banner hero-banner--sm mb-30px">
    <div class="container">
        <div class="hero-banner--sm__content">
            <h1>Contact Us</h1>
            <nav aria-label="breadcrumb" class="banner-breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<!--================ Hero sm Banner end =================-->


<!-- ================ contact section start ================= -->
<section class="section-margin">
    <div class="container">
        <div class="d-none d-sm-block mb-5 pb-4">
            <div id="map" style="height: 420px;"></div>
            <script>
                function initMap() {
                    var uluru = {lat: -25.363, lng: 131.044};
                    var grayStyles = [
                        {
                            featureType: "all",
                            stylers: [
                                {saturation: -90},
                                {lightness: 50}
                            ]
                        },
                        {elementType: 'labels.text.fill', stylers: [{color: '#A3A3A3'}]}
                    ];
                    var map = new google.maps.Map(document.getElementById('map'), {
                        center: {lat: -31.197, lng: 150.744},
                        zoom: 9,
                        styles: grayStyles,
                        scrollwheel: false
                    });
                }

            </script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

        </div>


        <div class="row">
            <div class="col-md-4 col-lg-3 mb-4 mb-md-0">
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-home"></i></span>
                    <div class="media-body">
                        <h3>California United States</h3>
                        <p>Santa monica bullevard</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-headphone"></i></span>
                    <div class="media-body">
                        <h3><a href="tel:454545654">00 (440) 9865 562</a></h3>
                        <p>Mon to Fri 9am to 6pm</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-email"></i></span>
                    <div class="media-body">
                        <h3><a href="mailto:support@colorlib.com">support@colorlib.com</a></h3>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-lg-9">
                <form action="#/" class="form-contact contact_form" action="contact_process.php" method="post"
                      id="contactForm" novalidate="novalidate">
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="form-group">
                                <input class="form-control" name="name" id="name" type="text"
                                       placeholder="Enter your name">
                            </div>
                            <div class="form-group">
                                <input class="form-control" name="email" id="email" type="email"
                                       placeholder="Enter email address">
                            </div>
                            <div class="form-group">
                                <input class="form-control" name="subject" id="subject" type="text"
                                       placeholder="Enter Subject">
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="form-group">
                                <textarea class="form-control different-control w-100" name="message" id="message"
                                          cols="30" rows="5" placeholder="Enter Message"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-center text-md-right mt-3">
                        <button type="submit" class="button button-contactForm">Send Message</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- ================ contact section end ================= -->
{% endblock %}

content/templates/website/features.html
{% extends 'website/base.html' %} {% load static %} {% load i18n %} {% block content %}
    <section class="hero-banner hero-banner--sm mb-30px">
        <div class="container">
            <div class="hero-banner--sm__content">
                <h1>Our Features</h1>
                <nav aria-label="breadcrumb" class="banner-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">{% trans 'Home' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Our Feature</li>
                    </ol>
                </nav>
            </div>
        </div>
    </section>
    <section class="section-margin">
        <div class="container">
            <div class="section-intro pb-85px text-center">
                <h2 class="section-intro__title">Features We Offer</h2>
                <p class="section-intro__subtitle">
                    Vel aliquam quis, nulla pede mi commodo tristique nam hac. Luctus torquent velit felis commodo
                    pellentesque nulla cras. Tincidunt hacvel alivquam quis nulla pede mi commodo tristique nam hac
                    luctus torquent
                </p>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <div class="row offer-single-wrapper">
                        <div class="col-lg-6 offer-single">
                            <div class="card offer-single__content text-center">
                            <span class="offer-single__icon">
                                <i class="ti-pencil-alt"></i>
                            </span>
                                <h4>{% trans 'Easy To Manage' %}</h4>
                                <p>{% trans "manage your own business in an easy and comfortable way" %}</p>
                                <div class="center">
                                    <button type="button" class="btn btn-secondary" data-toggle="popover" data-placement="bottom"
                                            data-content="{% trans "With a dark and modern design, we've achieved maximum comfort, when you work with Penge. This combined with our theory about never showing a button you don't need, has enabled us to make Poland's maybe easiest online accounting platform" %}">
                                        <i class="ti-help"></i>
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 offer-single">
                            <div class="card offer-single__content text-center">
                            <span class="offer-single__icon">
                                <i class="ti-ruler-pencil"></i>
                            </span>
                                <h4>Analytics Tool</h4>
                                <p>Posuere porttitor justo ornare dictum ultricies enim imperdiet integer habitant.</p>
                            </div>
                        </div>
                    </div>

                    <div class="row offer-single-wrapper">
                        <div class="col-lg-6 offer-single">
                            <div class="card offer-single__content text-center">
                            <span class="offer-single__icon">
                                <i class="ti-cut"></i>
                            </span>
                                <h4>Professionals Tools</h4>
                                <p>Posuere porttitor justo ornare dictum ultricies enim imperdiet integer habitant.</p>
                            </div>
                        </div>

                        <div class="col-lg-6 offer-single">
                            <div class="card offer-single__content text-center">
                            <span class="offer-single__icon">
                                <i class="ti-light-bulb"></i>
                            </span>
                                <h4>Ready Content</h4>
                                <p>Posuere porttitor justo ornare dictum ultricies enim imperdiet integer habitant.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="offer-single__img">
                        <img class="img-fluid" src="img/home/offer.png" alt=""/>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="section-padding bg-magnolia">
        <div class="container">
            <div class="section-intro pb-5 text-center">
                <h2 class="section-intro__title">Client Says Me</h2>
                <p class="section-intro__subtitle">Vel aliquam quis, nulla pede mi commodo tristique nam hac. Luctus
                    torquent velit felis commodo pellentesque nulla cras. Tincidunt hacvel alivquam</p>
            </div>

            <div class="owl-carousel owl-theme testimonial">
                <div class="testimonial__item text-center">
                    <div class="testimonial__img">
                        <img src="img/testimonial/testimonial1.png" alt=""/>
                    </div>
                    <div class="testimonial__content">
                        <h3>Stephen Mcmilan</h3>
                        <p>Executive, ACI Group</p>
                        <p class="testimonial__i">
                            Also made from. Give may saying meat there from heaven it lights face had is gathered god
                            earth light for life may itself shall whales made they're blessed whales also made from give
                            may saying meat. There from
                            heaven it lights face had also made from. Give may saying meat there from heaven
                        </p>
                    </div>
                </div>
                <div class="testimonial__item text-center">
                    <div class="testimonial__img">
                        <img src="img/testimonial/testimonial1.png" alt=""/>
                    </div>
                    <div class="testimonial__content">
                        <h3>Stephen Mcmilan</h3>
                        <p>Executive, ACI Group</p>
                        <p class="testimonial__i">
                            Also made from. Give may saying meat there from heaven it lights face had is gathered god
                            earth light for life may itself shall whales made they're blessed whales also made from give
                            may saying meat. There from
                            heaven it lights face had also made from. Give may saying meat there from heaven
                        </p>
                    </div>
                </div>
                <div class="testimonial__item text-center">
                    <div class="testimonial__img">
                        <img src="img/testimonial/testimonial1.png" alt=""/>
                    </div>
                    <div class="testimonial__content">
                        <h3>Stephen Mcmilan</h3>
                        <p>Executive, ACI Group</p>
                        <p class="testimonial__i">
                            Also made from. Give may saying meat there from heaven it lights face had is gathered god
                            earth light for life may itself shall whales made they're blessed whales also made from give
                            may saying meat. There from
                            heaven it lights face had also made from. Give may saying meat there from heaven
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="clients_logo_area section-padding">
        <div class="container">
            <div class="clients_slider owl-carousel">
                <div class="item">
                    <img src="img/clients-logo/c-logo-1.png" alt=""/>
                </div>
                <div class="item">
                    <img src="img/clients-logo/c-logo-2.png" alt=""/>
                </div>
                <div class="item">
                    <img src="img/clients-logo/c-logo-3.png" alt=""/>
                </div>
                <div class="item">
                    <img src="img/clients-logo/c-logo-4.png" alt=""/>
                </div>
                <div class="item">
                    <img src="img/clients-logo/c-logo-5.png" alt=""/>
                </div>
            </div>
        </div>
    </section>
{% endblock %}